baseurl         = "/"
theme = "hugo-casper-two"
languageCode    = "en-US"
disqusShortname = "blog-dannyrasch-com.disqus.com"
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "Blog"
  subtitle    = "Blog DannJRa"
  copyright   = "© 2019"
  
  #NOT WORKING
  cover       = "img/cover.jpg"
  
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = ["css/overrides.css"]
  RSSLink = ""

  twitterName = "Insider_DJR"
  #fbName = "fakeghost"
  githubName = "DannyJRa"
  linkedinName = "danny-rasch-2a22771b"
  mediumName = "dannjrasch"

  logo = "dr_small_png.png"
  orgName = "DJR"
  orgWebsite = "https://www.dannyrasch.com"
  orgDescription = "Here is a description placeholder for your org"

  showSupport = true

  author = "Danny J. R."
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "Bandung, ID"
  authorWebsite = "https://eueung.github.io"
  authorDescription = "Your description here"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"
  toc= true
  
[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Docker"
  url = "/tags/Docker/"
  weight = 100

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 99

#[[menu.main]]
#  name = "External"
#  url = "https://google.com/"
#  weight = 95


