baseurl         = "/"
theme = "hugo-casper-two"
languageCode    = "en-US"
disqusShortname = "blog-dannyrasch-com.disqus.com"
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true
#Enable emojis
enableEmoji=true
#Does not copy these files to public
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[params]
  title       = "Blog"
  subtitle    = "Blog DannyJRa"
  copyright   = "© 2021"
  #NOT WORKING
  cover       = "img/blog-cover.jpg"
  
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = ["css/overrides.css"]
  RSSLink = ""

  twitterName = "Insider_DJR"
  #fbName = "fakeghost"
  githubName = "DannyJRa"
  linkedinName = "danny-rasch-2a22771b"
  mediumName = "dannjrasch"

  logo = "singnature_DJR_white.png"
  orgName = "DJR"
  orgWebsite = "https://raschadvisory.com"
  orgDescription = "Here is a description placeholder for your org"

  showSupport = true

  author = "Danny J. R."
  authorAvatar = "img/avatar_danny.jpeg"
  authorLocation = "Zurich, CH"
  authorWebsite = "https://www.dannyrasch.com"
  authorDescription = "Cloud Advisor & Data Engineer"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"
  toc= true
  

  
[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Architecture"
  url = "/categories/Cloud/"
  weight = 199
  
[[menu.main]]
  name = "Analytics"
  url = "/categories/R/"
  weight = 197
  
[[menu.main]]
  name = "Engineering"
  url = "/categories/Python/"
  weight = 198

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 99

#Save in static folder any file, will be copied to public folder
#[[menu.main]]
#  name = "Slides"
#  url = "/slides/slides_test.html"
#  weight = 99

#[[menu.main]]
#  name = "External"
#  url = "https://google.com/"
#  weight = 95


