baseurl         = "/"
theme = "hugo-casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "Hugo Casper Two"
  subtitle    = "Port of Casper 2.x for Hugo"
  copyright   = "© 2019"

  cover       = "img/blog-cover.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = ["css/overrides.css"]
  RSSLink = ""

  twitterName = "faketryghost"
  #fbName = "fakeghost"
  githubName = "DannyJRa"
  linkedinName = "danny-rasch-2a22771b"
  mediumName = "DannyJRa"

  logo = "hugo-logo.png"
  orgName = "DJR"
  orgWebsite = "https://www.dannyrasch.com"
  orgDescription = "Here is a description placeholder for your org"

  showSupport = true

  author = "Danny J. R."
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "Bandung, ID"
  authorWebsite = "https://eueung.github.io"
  authorDescription = "Your description here"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"
  toc= true
  
[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Go"
  url = "/tags/golang/"
  weight = 100

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 99

[[menu.main]]
  name = "External"
  url = "https://google.com/"
  weight = 95


